#!/bin/bash -xe

if [ -e "/etc/environment" ]; then
    source /etc/environment
fi

if [ -e "/etc/farm-environment" ]; then
    source /etc/farm-environment
fi

GERRIT_DOCKER_DEFAULT_IMAGE='quay.io/swi-infra/gerrit:latest'
GERRIT_DOCKER_IMAGE=${GERRIT_DOCKER_IMAGE:-$GERRIT_DOCKER_DEFAULT_IMAGE}
GERRIT_DOCKER_NETWORK_NAME=${GERRIT_DOCKER_NETWORK_NAME:-gerrit}

if [ -z "$GERRIT_ROLE" ]; then
    if [[ "$MACHINE_TYPE" == "gerrit-mirror" ]]; then
        GERRIT_ROLE=mirror
    else
        GERRIT_ROLE=master
    fi
fi

# Kill/remove existing container
if docker inspect --type container gerrit; then
    docker kill gerrit || true
    docker rm --volumes gerrit || true
fi

docker pull "${GERRIT_DOCKER_IMAGE}"

# Create directories to store Gerrit files
mkdir -p /lstorage/services/gerrit/{etc,cache,index,plugins,logs,db,events-db,static}

# Generate private keys used for Gerrit SSH server
KEY_COMMENT="gerrit-code-review@$(hostname)"

if ! [ -e /lstorage/services/gerrit/ssh_host_rsa_key ]; then
    ssh-keygen -f /lstorage/services/gerrit/ssh_host_rsa_key -N '' -t 'rsa' -C "$KEY_COMMENT"
fi

if ! [ -e /lstorage/services/gerrit/ssh_host_dsa_key ]; then
    ssh-keygen -f /lstorage/services/gerrit/ssh_host_dsa_key -N '' -t 'dsa' -C "$KEY_COMMENT"
fi

if ! [ -e /lstorage/services/gerrit/ssh_host_ecdsa_key ]; then
    ssh-keygen -f /lstorage/services/gerrit/ssh_host_ecdsa_key -N '' -t 'ecdsa-sha2-nistp521' -C "$KEY_COMMENT"
fi

# Prepare configuration
rm -rf /tmp/gerrit-environment
if [ -e "/etc/gerrit-environment" ]; then
    cp /etc/gerrit-environment /tmp/gerrit-environment
else
    touch /tmp/gerrit-environment
fi

set_env() {
    local key=$1
    local value=$2

    echo "${key}=${value}" | tee -a /tmp/gerrit-environment
}

set_env JAVA_HEAPLIMIT "8g"

DOCKER_RUN_ARGS="--publish 29418:29418"

if [ ! -e "/lstorage/services/gerrit/gerrit_version" ]; then
    touch "/lstorage/services/gerrit/gerrit_version"
fi

if [[ "$GERRIT_ROLE" == "master" ]]; then
    echo "Role: Master"

    if [ -z "$HOST_HOSTNAME" ]; then
        # Use IP for URL
        HOST_HOSTNAME="${COREOS_PRIVATE_IPV4}"
    else
        set_env VIRTUAL_HOST "${HOST_HOSTNAME}"
        set_env VIRTUAL_PORT "8080"

        set_env LETSENCRYPT_HOST "${HOST_HOSTNAME}"
    fi

    set_env WEBURL "https://${HOST_HOSTNAME}"
    set_env HTTPD_LISTENURL "proxy-https://*:8080"

    set_env GET_PLUGINS "high-availability,avatars-gravatar:master-master"

elif [[ "$GERRIT_ROLE" == "mirror" ]]; then

    set_env JAVA_SLAVE "true"

else
    echo "Unknown role '$GERRIT_ROLE'"
    exit 1
fi

if ! docker network create "${GERRIT_DOCKER_NETWORK_NAME}"; then
    echo "Network already created"
fi

docker run \
            --name gerrit \
            --rm \
            --net "${GERRIT_DOCKER_NETWORK_NAME}" \
            ${DOCKER_RUN_ARGS} \
            --env-file /tmp/gerrit-environment \
            --volume /lstorage/services/gerrit/ssh_host_rsa_key:/var/gerrit/ssh_host_rsa_key \
            --volume /lstorage/services/gerrit/ssh_host_dsa_key:/var/gerrit/ssh_host_dsa_key \
            --volume /lstorage/services/gerrit/ssh_host_ecdsa_key:/var/gerrit/ssh_host_ecdsa_key \
            --volume /lstorage/services/gerrit/cache:/var/gerrit/review_site/cache \
            --volume /lstorage/services/gerrit/index:/var/gerrit/review_site/index \
            --volume /lstorage/services/gerrit/etc:/var/gerrit/review_site/etc \
            --volume /lstorage/services/gerrit/plugins:/var/gerrit/review_site/plugins \
            --volume /lstorage/services/gerrit/logs:/var/gerrit/review_site/logs \
            --volume /lstorage/services/gerrit/db:/var/gerrit/review_site/db \
            --volume /lstorage/services/gerrit/events-db:/var/gerrit/review_site/events-db \
            --volume /lstorage/services/gerrit/static:/var/gerrit/review_site/static \
            --volume /lstorage/services/gerrit/gerrit_version:/var/gerrit/review_site/gerrit_version \
            --volume /lstorage/git:/var/gerrit/review_site/git \
            ${GERRIT_DOCKER_IMAGE}

