#!/bin/bash -xe

docker pull jwilder/nginx-proxy
docker pull jrcs/letsencrypt-nginx-proxy-companion

docker run \
            --name nginx-proxy \
            --rm \
            -p 80:80 \
            -p 443:443 \
            --volume /lstorage/services/nginx/certs:/etc/nginx/certs:ro \
            --volume /lstorage/services/nginx/vhost.d:/etc/nginx/vhost.d \
            --volume /lstorage/services/nginx/share:/usr/share/nginx/html \
            --volume /var/run/docker.sock:/tmp/docker.sock:ro \
            --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
            jwilder/nginx-proxy &

sleep 10

docker run \
            --name letsencrypt \
            --rm \
            --volume /lstorage/services/nginx/certs:/etc/nginx/certs:rw \
            --volume /var/run/docker.sock:/var/run/docker.sock:ro \
            --volumes-from nginx-proxy \
            jrcs/letsencrypt-nginx-proxy-companion

